jobs:
  site-build:
    docker:
      - image: node:10.16.0-stretch-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Site
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths: dist
  site-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@mmis1000.me"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "b5:9e:e2:7f:ce:f4:bd:ec:31:b9:98:e5:86:2b:b7:dd"
      - run:
          name: Deploy site to gh-pages branch
          command: gh-pages --dist dist --message "[skip ci] Updates"
workflows:
  version: 2
  build:
    jobs:
      - site-build
      - site-deploy:
          requires:
            - site-build
          filters:
            branches:
              only: master